CREATE DATABASE IF NOT EXISTS QLDatVe CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE QLDatVe;

CREATE TABLE TAI_KHOAN (
    MaTaiKhoan INT AUTO_INCREMENT PRIMARY KEY,
    TenDangNhap VARCHAR(50) NOT NULL UNIQUE,
    MatKhau VARCHAR(255) NOT NULL,
    HoTen NVARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    SoDienThoai VARCHAR(15),
    VaiTro ENUM('Admin','KhachHang','NhanVien') NOT NULL,
    TrangThai ENUM('HoatDong','NgungHoatDong') NOT NULL
);

CREATE TABLE KHACH_HANG (
    MaKhachHang INT AUTO_INCREMENT PRIMARY KEY,
    MaTaiKhoan INT NOT NULL UNIQUE,
    NgaySinh DATE,
    GioiTinh ENUM('Nam','Nu','Khac'),
    DiaChi VARCHAR(500),
    FOREIGN KEY (MaTaiKhoan) REFERENCES TAI_KHOAN(MaTaiKhoan)
);

CREATE TABLE NHAN_VIEN (
    MaNhanVien INT AUTO_INCREMENT PRIMARY KEY,
    MaTaiKhoan INT NOT NULL UNIQUE,
    ChucVu NVARCHAR(100) NOT NULL,
    NgaySinh DATE,
    GioiTinh ENUM('Nam','Nu','Khac'),
    DiaChi NVARCHAR(500),
    NgayVaoLam DATE,
    FOREIGN KEY (MaTaiKhoan) REFERENCES TAI_KHOAN(MaTaiKhoan)
);

CREATE TABLE BAN_TO_CHUC (
    MaBTC INT AUTO_INCREMENT PRIMARY KEY,
    TenToChuc NVARCHAR(255) NOT NULL,
    MoTa TEXT,
    Logo VARCHAR(255),
    Email VARCHAR(255),
    SoDienThoai VARCHAR(15)
);

CREATE TABLE DIA_DIEM_TO_CHUC (
    MaDiaDiem INT AUTO_INCREMENT PRIMARY KEY,
    TenDiaDiem NVARCHAR(255) NOT NULL,
    DiaChiChiTiet NVARCHAR(500) NOT NULL,
    ThanhPho NVARCHAR(100) NOT NULL,
    SucChuaToiDa INT NOT NULL,
    MoTa TEXT
);

CREATE TABLE LOAI_SU_KIEN (
    MaLoaiSuKien INT AUTO_INCREMENT PRIMARY KEY,
    TenLoai NVARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE THE_LOAI_AM_NHAC (
    MaTheLoai INT AUTO_INCREMENT PRIMARY KEY,
    TenTheLoai NVARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE SU_KIEN (
    MaSuKien INT AUTO_INCREMENT PRIMARY KEY,
    MaBTC INT NOT NULL,
    MaDiaDiem INT NOT NULL,
    MaLoaiSuKien INT NOT NULL,
    TenSuKien NVARCHAR(255) NOT NULL,
    AnhBia VARCHAR(255) NOT NULL,
    MoTa TEXT,
    DiemNoiBat TEXT,
    DieuKienVaDieuKhoan TEXT,
    ThoiGianBatDau DATETIME NOT NULL,
    ThoiGianKetThuc DATETIME NOT NULL,
    TrangThai ENUM('SapDienRa','DangMoBan','DaKetThuc','DaHuy') NOT NULL,
    FOREIGN KEY (MaBTC) REFERENCES BAN_TO_CHUC(MaBTC),
    FOREIGN KEY (MaDiaDiem) REFERENCES DIA_DIEM_TO_CHUC(MaDiaDiem),
    FOREIGN KEY (MaLoaiSuKien) REFERENCES LOAI_SU_KIEN(MaLoaiSuKien)
);

CREATE TABLE MERCHANDISE (
    MaMerch INT AUTO_INCREMENT PRIMARY KEY,
    TenMerch NVARCHAR(255) NOT NULL,
    MoTa TEXT,
    GiaBan DECIMAL(12,2) NOT NULL,
    SoLuongTon INT DEFAULT 0,
    AnhSanPham VARCHAR(255) NOT NULL,
    TrangThai ENUM('DangBan','NgungBan') NOT NULL,
    ChinhSachDoiTra TEXT,
    HuongDanBaoQuan TEXT
);

CREATE TABLE NGHE_SI (
    MaNgheSi INT AUTO_INCREMENT PRIMARY KEY,
    TenNgheSi NVARCHAR(255) NOT NULL,
    NgheDanh NVARCHAR(255),
    QuocGia NVARCHAR(100),
    TieuSu TEXT,
    AnhDaiDien VARCHAR(255)
);

CREATE TABLE KHU_VUC_SU_KIEN (
    MaKhuVuc INT AUTO_INCREMENT PRIMARY KEY,
    MaSuKien INT NOT NULL,
    TenKhuVuc NVARCHAR(100) NOT NULL,
    SucChua INT NOT NULL,
    MoTa TEXT,
    FOREIGN KEY (MaSuKien) REFERENCES SU_KIEN(MaSuKien)
);

CREATE TABLE HANG_VE (
    MaHangVe INT AUTO_INCREMENT PRIMARY KEY,
    MaKhuVuc INT NOT NULL,
    TenHangVe NVARCHAR(100) NOT NULL,
    GiaVe DECIMAL(12,2) NOT NULL,
    SoLuongMoBan INT NOT NULL,
    SoLuongDaBan INT DEFAULT 0,
    ThoiGianMoBan DATETIME NOT NULL,
    ThoiGianKetThucBan DATETIME NOT NULL,
    QuyenLoi TEXT,
    FOREIGN KEY (MaKhuVuc) REFERENCES KHU_VUC_SU_KIEN(MaKhuVuc)
);

CREATE TABLE GHE_NGOI (
    MaGhe INT AUTO_INCREMENT PRIMARY KEY,
    MaKhuVuc INT NOT NULL,
    HangGhe VARCHAR(10) NOT NULL,
    SoGhe VARCHAR(10) NOT NULL,
    TrangThai ENUM('Trong','DangGiu','DaBan') NOT NULL,
    FOREIGN KEY (MaKhuVuc) REFERENCES KHU_VUC_SU_KIEN(MaKhuVuc)
);

CREATE TABLE NHAN_VIEN_SU_KIEN (
    MaNhanVien INT NOT NULL,
    MaSuKien INT NOT NULL,
    VaiTro VARCHAR(100) NOT NULL,
    PRIMARY KEY (MaNhanVien, MaSuKien),
    FOREIGN KEY (MaNhanVien) REFERENCES NHAN_VIEN(MaNhanVien),
    FOREIGN KEY (MaSuKien) REFERENCES SU_KIEN(MaSuKien)
);

CREATE TABLE SU_KIEN_TL_AM_NHAC (
    MaSuKien INT NOT NULL,
    MaTheLoai INT NOT NULL,
    PRIMARY KEY (MaSuKien, MaTheLoai),
    FOREIGN KEY (MaSuKien) REFERENCES SU_KIEN(MaSuKien),
    FOREIGN KEY (MaTheLoai) REFERENCES THE_LOAI_AM_NHAC(MaTheLoai)
);

CREATE TABLE THAM_GIA_BIEU_DIEN (
    MaSuKien INT NOT NULL,
    MaNgheSi INT NOT NULL,
    ThuTuBieuDien INT NOT NULL,
    ThoiGianBieuDien DATETIME NOT NULL,
    PRIMARY KEY (MaSuKien, MaNgheSi),
    FOREIGN KEY (MaSuKien) REFERENCES SU_KIEN(MaSuKien),
    FOREIGN KEY (MaNgheSi) REFERENCES NGHE_SI(MaNgheSi)
);

CREATE TABLE DON_HANG (
    MaDonHang INT AUTO_INCREMENT PRIMARY KEY,
    MaKhachHang INT NOT NULL,
    NgayDat DATETIME NOT NULL,
    TongTien DECIMAL(12,2) NOT NULL,
    TrangThai ENUM('ChoThanhToan','DaThanhToan','DaHuy') NOT NULL,
    FOREIGN KEY (MaKhachHang) REFERENCES KHACH_HANG(MaKhachHang)
);

CREATE TABLE THANH_TOAN (
    MaThanhToan INT AUTO_INCREMENT PRIMARY KEY,
    MaDonHang INT NOT NULL,
    PhuongThucThanhToan NVARCHAR(50) NOT NULL,
    SoTien DECIMAL(12,2) NOT NULL,
    ThoiGianThanhToan DATETIME,
    MaGiaoDich VARCHAR(100) UNIQUE,
    TrangThai ENUM('ChoThanhToan','ThanhCong','ThatBai') NOT NULL,
    FOREIGN KEY (MaDonHang) REFERENCES DON_HANG(MaDonHang)
);

CREATE TABLE VE (
    MaVe INT AUTO_INCREMENT PRIMARY KEY,
    MaDonHang INT NOT NULL,
    MaHangVe INT NOT NULL,
    MaGhe INT,
    MaSuKien INT NOT NULL,
    MaQR VARCHAR(255) NOT NULL UNIQUE,
    MaVeDienTu VARCHAR(100) NOT NULL UNIQUE,
    TrangThai ENUM('ChoSuDung','DaSuDung','DaHuy') NOT NULL,
    ThoiGianCheckIn DATETIME,
    FOREIGN KEY (MaDonHang) REFERENCES DON_HANG(MaDonHang),
    FOREIGN KEY (MaHangVe) REFERENCES HANG_VE(MaHangVe),
    FOREIGN KEY (MaGhe) REFERENCES GHE_NGOI(MaGhe),
    FOREIGN KEY (MaSuKien) REFERENCES SU_KIEN(MaSuKien)
);

CREATE TABLE VE_TANG (
    MaVeTang INT AUTO_INCREMENT PRIMARY KEY,
    MaVe INT NOT NULL,
    MaTaiKhoanNguoiTang INT NOT NULL,
    TenNguoiNhan NVARCHAR(255) NOT NULL,
    EmailNguoiNhan VARCHAR(255) NOT NULL,
    SdtNguoiNhan VARCHAR(15),
    LoaiThiep NVARCHAR(100),
    LoiChuc TEXT,
    FOREIGN KEY (MaVe) REFERENCES VE(MaVe),
    FOREIGN KEY (MaTaiKhoanNguoiTang) REFERENCES TAI_KHOAN(MaTaiKhoan)
);

CREATE TABLE CT_DON_HANG_MERCHANDISE (
    MaDonHang INT NOT NULL,
    MaMerch INT NOT NULL,
    SoLuong INT NOT NULL,
    DonGia DECIMAL(12,2) NOT NULL,
    PRIMARY KEY (MaDonHang, MaMerch),
    FOREIGN KEY (MaDonHang) REFERENCES DON_HANG(MaDonHang),
    FOREIGN KEY (MaMerch) REFERENCES MERCHANDISE(MaMerch)
);

CREATE TABLE GIU_CHO_VE (
    MaGiuCho INT AUTO_INCREMENT PRIMARY KEY,
    MaKhachHang INT NOT NULL,
    ThoiGianBatDau DATETIME NOT NULL,
    ThoiGianHetHan DATETIME NOT NULL,
    TrangThai ENUM('DangGiuCho','DaHetHan','DaThanhToan','DaHuy') NOT NULL,
    FOREIGN KEY (MaKhachHang) REFERENCES KHACH_HANG(MaKhachHang)
);

CREATE TABLE CHI_TIET_GIU_CHO (
    MaGiuCho INT NOT NULL,
    MaHangVe INT NOT NULL,
    SoLuong INT NOT NULL,
    PRIMARY KEY (MaGiuCho, MaHangVe),
    FOREIGN KEY (MaGiuCho) REFERENCES GIU_CHO_VE(MaGiuCho),
    FOREIGN KEY (MaHangVe) REFERENCES HANG_VE(MaHangVe)
);

CREATE TABLE DANH_MUC_BAI_VIET (
    MaDanhMuc INT AUTO_INCREMENT PRIMARY KEY,
    TenDanhMuc NVARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE TIN_TUC_BAI_VIET (
    MaBaiViet INT AUTO_INCREMENT PRIMARY KEY,
    MaNhanVien INT NOT NULL,
    TieuDe NVARCHAR(255) NOT NULL,
    NoiDung LONGTEXT NOT NULL,
    AnhDaiDien VARCHAR(255),
    NgayDang DATETIME NOT NULL,
    MaDanhMuc INT NOT NULL,
    MaSuKienLienQuan INT,
    FOREIGN KEY (MaNhanVien) REFERENCES NHAN_VIEN(MaNhanVien),
    FOREIGN KEY (MaDanhMuc) REFERENCES DANH_MUC_BAI_VIET(MaDanhMuc),
    FOREIGN KEY (MaSuKienLienQuan) REFERENCES SU_KIEN(MaSuKien)
);
